## Introduction to Python Exercises

Before you turn this problem in, make sure everything runs as expected. First, restart the kernel (in the menubar, select Kernel → Restart) and then run all cells (in the menubar, select Cell → Run All).  You can speak with others regarding the assignment but all work must be your own. 


### This is a 30 point assignment graded from answers to questions and automated tests that should be run at the bottom. Be sure to clearly label all of your answers and commit final tests at the end.  


**You may find it useful to go through the notebooks from the course materials when doing these exercises.**

In [1]:
NAME = "Jason Kuruzovich"
COLLABORATORS = ["Alyssa Hacker"]  #You can speak with others regarding the assignment, but all typed work must be your own.

### Installing Packages Locally
If you are working locally you will need to install *gradememaybe* at a minimum.  The code below should handle it. Uncomment (remove #s) this cell and then run it.

*If you are running the code on lab.analyticsdojo.com, please skip this next cell. 


In [8]:
%%bash    
conda install -y pip
pip install -r requirements.txt 

Solving environment: ...working... done

# All requested packages already installed.



In [1]:
#This loads the grading software.  If you later get a "failed to import OK.py" you need to rerun.
from client.api.notebook import Notebook
ok = Notebook('hm02.ok')
_ = ok.auth(inline=True)

### This Loads a Testing Array 
- This runs tests against your b array.  If you complete the assingment correctly, you will pass the tests. 
- **If you attempt to fake passing the tests you will receive a 0 on the assignment and it will be considered an ethical violation.**

## Exercise-Packages

This creates an Numpy array. Numpy is a common package that we will use to work with arrays. You can read more about Numpy [here](http://www.numpy.org/). 

```
a = np.array([2,3,4])
print(a)
```

To get this to work, you will have to make sure that the numpy(np) package is installed. 


In [12]:
q1_question= """
(1) Verify that Numpy is installed. How did you know?  
Describe how you would you install it if it wasn't installed?
"""
#You must assign your answer to q1. 
q1_answer="""
Enter your answer here.
"""

(2) Fix the cell below so that a is a numpy array.

In [2]:
import numpy as np
a = np.array([5,6,7,8])
print(a, type(a))


[5 6 7 8] <class 'numpy.ndarray'>


In [5]:
_ = ok.grade('q02')

In [4]:
import pandas as pd

In [1]:
!conda uninstall -y matplotlib 

Solving environment: done

## Package Plan ##

  environment location: /anaconda3/envs/grademe

  removed specs: 
    - matplotlib


The following packages will be REMOVED:

    matplotlib: 2.2.3-py36h0e0179f_0 conda-forge

Preparing transaction: done
Verifying transaction: done
Executing transaction: done


(3) Create a numpy array `b` with the values 12, 13, 14, 15.



In [6]:
#<insert q3 code here>



[12 13 14 15]


In [13]:
_ = ok.grade('q03')

## Exercise - Operations on Variables




In [ ]:
q4_question= """
(4) Describe what happens when you multiply an integer times a boolean? 
What is the resulting type? Provide examples.
"""
#You must assign your answer to q4_answer. 
q4_answer="""
Enter your answer here.
"""

In [ ]:
q5_question= """
(5) Describe happens when you try to multiply an integer value times a null?
"""
#You must assign your answer to q5_answer. 
q5_answer="""
Enter your answer here.
"""


(6) Take 5 to the power of 4 and assign it to a variable `c`. Then transform the variable to c to a type `float`. 

In [39]:
#<insert q6 code here>

float

In [2]:
_ = ok.grade('q06')

## Exercise-Lists
Hint: [This list of functions on lists is useful.](https://docs.python.org/3/tutorial/datastructures.html#more-on-lists) as is the process of tab completion (using tab to find available methods of an object).

(7) Create a list `elist1` with the following values (1,2,3,4,5).<br>


In [48]:
#<insert q7 code here>
elist1=[1,2,3,4,5]
type(elist1)

list

In [52]:
_ = ok.grade('q07')

(8) Create a new list `elist2` by first creating a copy of elist1 and then reversing the order.

*HINT, remember there is a specify way to 


In [59]:
#<insert q8 code here>
elist2 = elist1.copy()
elist2.reverse()
elist2

[5, 4, 3, 2, 1]

In [60]:
_ = ok.grade('q08')

(9) Create a new list `elist3` by first creating a copy of elist1 and then adding 7 8 9 to the end. (Hint: Search for a different function if appending doesn't work.) 



In [65]:
#<insert q9 code here>
elist3 = elist1.copy()
elist3.extend([7,8,9])
elist3

[1, 2, 3, 4, 5, 7, 8, 9]

In [68]:
_ = ok.grade('q09')

(10) Create a new list `elist4` by first creating a copy of elist3 and then insert 6 between 5 and 7.

In [72]:
#<insert q10 code here>
elist4 = elist3.copy()
elist4.insert(5,6)
elist4

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [73]:
_ = ok.grade('q10')

## Exercise-Sets/Dictionary

This [link to documentation on sets](https://docs.python.org/3/tutorial/datastructures.html#sets) may be useful.

(11) Create a set `eset1` with the following values (1,2,3,4,5).


In [75]:
#<insert q11 code here>
eset1={1,2,3,4,5}

In [78]:
_ = ok.grade('q11')


(12) Create a new set `eset2` the following values (1,3,6).



In [79]:
#<insert q12 code here>
eset1={1,3,6}

In [80]:
_ = ok.grade('q12')

(13) Create a new set `eset3` that is `eset1-eset2`.



In [ ]:
#<insert q13 code here>

In [ ]:
_ = ok.grade('q13')

(14) Create a new set `eset4` that is the union of `eset1+eset2`.


In [ ]:
#<insert q14 code here>

In [ ]:
_ = ok.grade('q14')


(15) Create a new set `eset5` that includes values that are in both `eset1` and `eset2` (intersection).



In [ ]:
#<insert q15 code here>

In [ ]:
_ = ok.grade('q15')

(16) Create a new dict `edict1` with the following keys and associated values: st1=45; st2=32; st3=40; st4=31.

*Hint: There is a good section on dictionaries [here](https://docs.python.org/3/tutorial/datastructures.html#dictionaries).


In [82]:
#<insert q16 code here>
edict1={'st1': 45, 'st2': 32, 'st3':40, 'st4':31}

In [84]:
_ = ok.grade('q16')


(17) Create a new variable `key1` from edict1 where the *key* is `st3`.

In [ ]:
#<insert q17 code here>

In [ ]:
_ = ok.grade('q17')

# Exercise-Numpy Array

(18) Create a new numpy array `nparray1` that is 3x3 and all the number 3 (should be integer type).



In [87]:
#<insert q18 code here>
nparray1= np.array([3,3,3,3,3,3,3,3,3])
nparray1 = nparray1.reshape(3,3)
nparray1

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [91]:
_ = ok.grade('q18')


(19) Create a new variable `nparray1sum` that sums all of column 0.


In [93]:
#<insert q19 code here>
nparray1sum = nparray1[::,0:1:].sum()

In [99]:
_ = ok.grade('q19')

(20) Create a new variable `nparray1mean` that takes the average of column 0.


In [95]:
#<insert q20 code here>
nparray1mean = nparray1[::,0:1:].mean()

In [97]:
_ = ok.grade('q20')

(21) Create a new numpy array `nparray2` that selects only column 1 of `nparray1` (all rows).


In [105]:
#<insert q21 code here>
nparray2 = nparray1[0::,0:1:]
nparray2

array([[3],
       [3],
       [3]])

In [108]:
_ = ok.grade('q21')

(22) Create a new numpy array `nparray3` that is equal to `nparray1` times `2` (you should not alter `nparray1`).


In [109]:
#<insert q22 code here>
nparray3 = nparray1*2

In [112]:
_ = ok.grade('q22')

(23) Create a new numpy array nparray4 that is a verticle stack of `nparray1` and `nparray3`.

In [113]:
#<insert q23 code here>
nparray4 = np.vstack([nparray1,nparray3])

In [116]:
_ = ok.grade('q23')

## Exercise-Pandas

For these you will need to import the iris dataset. You should find the file `iris.csv` in the main directory.  

While we showed 2 ways of importing a csv, you should use the `read_csv` method of Pandas to load the csv into a dataframe called `df`. 


In [6]:
#Load iris.csv into a Pandas dataframe here.
#Check out the first few rows with the head command. 
import pandas as pd
df = pd.read_csv('iris.csv')

In [2]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
5             5.4          3.9           1.7          0.4     setosa
6             4.6          3.4           1.4          0.3     setosa
7             5.0          3.4           1.5          0.2     setosa
8             4.4          2.9           1.4          0.2     setosa
9             4.9          3.1           1.5          0.1     setosa
10            5.4          3.7           1.5          0.2     setosa
11            4.8          3.4           1.6          0.2     setosa
12            4.8          3.0           1.4          0.1     setosa
13            4.3          3.0           1.1          0.1     setosa
14            5.8          4.0           1.2          0.2     setosa
15            5.7          4.4           1.5          0.4     setosa
16            5.4          3.9           1.3          0.4     setosa
17            5.1          3.5           1.4          0.3     setosa
18            5.7          3.8           1.7          0.3     setosa
19            5.1          3.8           1.5          0.3     setosa
20            5.4          3.4           1.7          0.2     setosa
21            5.1          3.7           1.5          0.4     setosa
22            4.6          3.6           1.0          0.2     setosa
23            5.1          3.3           1.7          0.5     setosa
24            4.8          3.4           1.9          0.2     setosa
25            5.0          3.0           1.6          0.2     setosa
26            5.0          3.4           1.6          0.4     setosa
27            5.2          3.5           1.5          0.2     setosa
28            5.2          3.4           1.4          0.2     setosa
29            4.7          3.2           1.6          0.2     setosa
..            ...          ...           ...          ...        ...
120           6.9          3.2           5.7          2.3  virginica
121           5.6          2.8           4.9          2.0  virginica
122           7.7          2.8           6.7          2.0  virginica
123           6.3          2.7           4.9          1.8  virginica
124           6.7          3.3           5.7          2.1  virginica
125           7.2          3.2           6.0          1.8  virginica
126           6.2          2.8           4.8          1.8  virginica
127           6.1          3.0           4.9          1.8  virginica
128           6.4          2.8           5.6          2.1  virginica
129           7.2          3.0           5.8          1.6  virginica
130           7.4          2.8           6.1          1.9  virginica
131           7.9          3.8           6.4          2.0  virginica
132           6.4          2.8           5.6          2.2  virginica
133           6.3          2.8           5.1          1.5  virginica
134           6.1          2.6           5.6          1.4  virginica
135           7.7          3.0           6.1          2.3  virginica
136           6.3          3.4           5.6          2.4  virginica
137           6.4          3.1           5.5          1.8  virginica
138           6.0          3.0           4.8          1.8  virginica
139           6.9          3.1           5.4          2.1  virginica
140           6.7          3.1           5.6          2.4  virginica
141           6.9          3.1           5.1          2.3  virginica
142           5.8          2.7           5.1          1.9  virginica
143           6.8          3.2           5.9          2.3  virginica
144           6.7          3.3           5.7          2.5  virginica
145           6.7          3.0           5.2          2.3  virginica
146

(24) Create a variable `df_rows` that includes the number of rows in the `df` dataframe.

In [8]:
df.iloc[3,0]

4.6

In [8]:
#<insert q24 code here>
df_rows=150

In [9]:
_ = ok.grade('q24')

KeyError: 'image/svg+xml'

(25) Create a new dataframe `df_train` that includes the first half of the `df` dataframe. Create a new dataframe `df_test` that includes the second half. 

In [3]:
#<insert q25 code here>
df_train = df.iloc[:75]
df_test = df.iloc[75:]

df_test.iloc[74,1]

3.0

In [4]:
_ = ok.grade('q25')

NameError: name 'ok' is not defined

(26) Create a new Pandas Series `sepal_length` from the `sepal_length` column of the df dataframe.

In [12]:
import matplotlib

In [10]:

#<insert q26 code here>
sepal_length=pd.Series(df['sepal_length'])
type(sepal_length)

In [13]:
_ = ok.grade('q26')

KeyError: 'image/svg+xml'


(24) Using, the Iris dataset, find the mean of the `sepal_length` series in our sample and assign it to the `sepal_length_mean` variable. You should round the result to 3 digits after the decimal. 

```
#Round example
a=99.9999999999999
#For example, the following will round a to 2 digits.
b = round(a,2)   

```

In [171]:
#<insert q27 code here>
sepal_length_mean = round(np.mean(df['sepal_length']),3)
sepal_length_mean

5.843

In [173]:
_ = ok.grade('q27')

## Run these Tests before Submission
This is a collection of all of the tests from the exercises above which will be used for grading.  

In [174]:
import os
_ = [ok.grade(q[:-3]) for q in os.listdir("tests") if q.startswith('q')]